default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kaname_development

test:
  <<: *default
  database: kaname_test

production:
  <<: *default
  database: kaname_production
  username: kaname
  password: <%= ENV['KANAME_DATABASE_PASSWORD'] %>
